#!/bin/bash

run_docker_command() {
    local command=$1
    docker compose exec -T worker bash -c "$command"
}

# PyLint
run_docker_command "pylint --rcfile=/usr/src/app/pylintrc /usr/src/app/*.py > /usr/src/app/pylint_result.log"

# autopep8
run_docker_command "autopep8 --in-place --aggressive --aggressive /usr/src/app/*.py"

# black
run_docker_command "black /usr/src/app/*.py"

# isort
run_docker_command "isort /usr/src/app/*..py"