default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>

development:
  <<: *default
  database: rails_setlist_analyzer_development

test:
  <<: *default
  database: rails_setlist_analyzer_test