name: Worker CI

on:
  pull_request:
    paths:
      - 'workers/**'
  push:
    branches:
      - main
      - develop

jobs:
  flask:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./workers
    env:
      AUDIO_PATH: '/'
      PYTHONPATH: ${{ github.workspace }}/workers
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy fixtures
      run: |
        mkdir -p ./tests/fixtures/sample
        cp -r ../fixtures/* ./tests/fixtures/sample
    - name: Run Lint
      run: |
        pylint --rcfile=./pylintrc --ignore=venv .
    - name: Run Tests
      run: |
        pytest