name: Frontend CI

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/build_and_test_frontend.yml'
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/build_and_test_frontend.yml'
    branches:
      - main
      - develop

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: yarn install
    - name: Run lint
      run: yarn lint
