name: Worker CI

on:
  pull_request:
    paths:
      - 'workers/**'
      - '.github/workflows/build_and_test_worker.yml'
  push:
    paths:
      - 'workers/**'
      - '.github/workflows/build_and_test_worker.yml'
    branches:
      - main
      - develop

jobs:
  flask:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./workers
    env:
      AUDIO_PATH: '/'
      PYTHONPATH: ${{ github.workspace }}/workers
      SKIP_LONG_TESTS: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy fixtures
      run: |
        mkdir -p ./tests/fixtures/sample
        cp -r ../fixtures/* ./tests/fixtures/sample
    - name: Run Lint
      run: |
        pylint --rcfile=./pylintrc app.py --verbose
    - name: Run Tests
      run: |
        pytest -s