name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  rails:
    runs-on: ubuntu-latest
    env:
      AUDIO_PATH: '/'
      REDIS_URL: redis://redis:6379/0
      DATABASE_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
      RAILS_ENV: test
    services:
      db:
        image: mysql:8.0.25
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin -h ${{ env.DATABASE_HOST }} -P 3306 -u root -p${{ env.MYSQL_ROOT_PASSWORD }} ping --silent; do
          echo 'waiting for mysql to be connectable...'
          sleep 1
        done
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'

    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems- 

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        gem install bundler
        bundle install
    
    - name: Set up database
      run: |
        sudo apt-get install -y libmysqlclient-dev
        bundle exec rake db:create ridgepole:apply

    - name: Run tests
      run: |
        mkdir -p ./spec/fixtures/audios/
        bundle exec rspec

    - name: Run Rubocop
      run: |
        bundle exec rubocop

  flask:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./workers
    env:
      AUDIO_PATH: '/'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy fixtures
      run: |
        mkdir -p ./tests/fixtures/sample
        cp -r ../fixtures/* ./tests/fixtures/sample
    - name: Run Lint
      run: |
        export PYTHONPATH=$PWD
        pylint --rcfile=./pylintrc --ignore=venv .
    - name: Run Tests
      run: |
        export PYTHONPATH=$PWD
        pytest

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: yarn install
    - name: Run lint
      run: yarn lint
